version: '3'
services:
  web:
    image: blocklinkbackend
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    working_dir: /code
    command: "-w 4 -b 0.0.0.0:5000 app:app"
    entrypoint:
    - gunicorn
  celery:
    image: blocklinkbackend
    volumes:
    - .:/code
    - logvolume02:/var/log
    working_dir: /code
    command: "-A app:celery worker -l info --concurrency=4 -f ./logs/%I.log -B"
    entrypoint:
    - celery
volumes:
  logvolume01: {}
  logvolume02: {}
